#
# Buildfile for r-node
#
import Options
from os import unlink, symlink, popen
from os.path import exists 

srcdir = '.'
blddir = 'build/'

VERSION = '0.0.1'

def set_options(opt):
  opt.tool_options('compiler_cxx')

def configure(conf):
  conf.check_tool('compiler_cxx')
  conf.check_tool('node_addon')

  rserve_base = "/usr/lib/R/site-library/Rserve"
  r_base = "/usr/lib/R"

  # doesn't appear to be a conf program for R that serves this paths.
  # also, until I figure out why the Rserve library is so badly named 
  # and non-working, use this purpose built one.

  conf.env['CXXFLAGS'] = ['-g']

  conf.env.append_value("LIBPATH_R", r_base + "/lib")
  conf.env.append_value("LIBPATH_RSERVE", "3rdparty/rserve/lib")

  conf.env.append_value("LIB_R", "R")
  conf.env.append_value("LIB_RSERVE", "rserve")
  conf.env.append_value("LIB_CRYPT", "crypt")

def build(bld):
  obj = bld.new_task_gen('cxx', 'shlib', 'node_addon')
  obj.target = 'binding'
  obj.source = ["Rconnection.cc", "binding.cc"]
  obj.includes = ['include']
  obj.uselib = "R CRYPT"
  
